#done
grace: 20
#done
after-elimination-hunter: true
#done
border:
  #donw
  world: "world"
  #done
  starting-size: 50.0
  end-size: 1.0
  duration: 20
  #donw
  eliminates: true
  start-after-grace: true